name: building-checking
run-name: ${{ github.actor }} is building software
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create a virtual environment
        run: python -m venv venv
      - name: Activate the virtual environment
        run: source venv/bin/activate
      - name: Install prereqs
        run: |
          chmod u+x ./prereqs.sh
          ./prereqs.sh
      - name: Build
        run: |
          chmod u+x ./build.sh
          ./build.sh
