name: unittest-checking
run-name: ${{ github.actor }} is testing software
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        working-directory: ./src
        run: |
          python test/test.py
