name: unittest-checking
run-name: ${{ github.actor }} is testing software
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          ./prereqs.sh
      - name: Run tests
        working-directory: ./src
        run: |
          python test/test.py
